# Company Information
company_name: Adassa Store
copyright: D P Bennett & Associates Ltd.
domain_name: store.adassa.com.jm
address_line: Kingston
country: Jamaica
company_email: mail@adassa.com.jm
description: This is the Adassa Store website.
meta_description: business management system, engineering, information technology, personal development, personal products 

# Site Information
title: Adassa Store
author: Desmond Bennett
baseurl: ""
url: https://store.adassa.com.jm

# Social Links
facebook_link: https://www.facebook.com/desmondpbennett
twitter_link: https://twitter.com/DPB_and_A
github_link: https://github.com/Adassa-Enterprise-Solutions/

disqus:
  username: adassa

# Build settings
markdown: kramdown

permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate-v2
  - jekyll-disqus

jekyll_admin:
  hidden_links:
    - configuration
  homepage: "pages"  
